// <auto-generated />
using System;
using MagicVilla_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetersSquared")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupants")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            DateCreate = new DateTime(2023, 5, 28, 2, 12, 3, 399, DateTimeKind.Local).AddTicks(4731),
                            Details = "",
                            Fee = 200.0,
                            ImageUrl = "",
                            MetersSquared = 50,
                            Name = "Villa Real",
                            Occupants = 5,
                            UpdateDate = new DateTime(2023, 5, 28, 2, 12, 3, 399, DateTimeKind.Local).AddTicks(4739)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            DateCreate = new DateTime(2023, 5, 28, 2, 12, 3, 399, DateTimeKind.Local).AddTicks(4741),
                            Details = "",
                            Fee = 150.0,
                            ImageUrl = "",
                            MetersSquared = 50,
                            Name = "Premium Vista a la Piscina",
                            Occupants = 4,
                            UpdateDate = new DateTime(2023, 5, 28, 2, 12, 3, 399, DateTimeKind.Local).AddTicks(4742)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
